version: "1"
services:
  simple-tasks:
    build:
      context: .
    container_name: simple-tasks
    restart: always
    depends_on:
      - db
    ports:
      - 80:8080
    environment:
      - DB_ADDRESS=${DB_ADDRESS}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}

  db:
    image: bitnami/postgresql:latest
    container_name: db
    restart: always
#    volumes:
#      - .db/:/bitnami/postgresql
    environment:
      - POSTGRESQL_DATABASE=${DB_NAME}
      - POSTGRESQL_USERNAME=${DB_USER}
      - POSTGRESQL_PASSWORD=${DB_PASSWORD}
      - POSTGRESQL_PORT_NUMBER=${DB_PORT}

  adminer:
    image: adminer:latest
    restart: always
    ports:
      - 8080:8080
